version: 2

sources:
  - name: fink_finances
    tables:
      - name: amex_transactions
      - name: anntaylor_transactions
      - name: apple_transactions
      - name: barclay_transactions
      - name: capital_one_transactions
      - name: chase_amazon_transactions
      - name: chase_checking_transactions
      - name: chase_freedom_transactions
      - name: chase_sapphire_dan_transactions
      - name: chase_sapphire_transactions
      - name: citi_transactions
      - name: discover_transactions
      - name: first_republic_transactions
      - name: jetblue_transactions
      - name: nordstrom_transactions
      - name: tjmaxx_transactions

  - name: raw_transactions
    tables:
      - name: amex_transactions_cumulative
      - name: anntaylor_transactions_cumulative
      - name: apple_transactions_cumulative
      - name: barclay_transactions_cumulative
      - name: chase_transactions_cumulative
      - name: citi_transactions_cumulative
      - name: discover_transactions_cumulative
      - name: nordstrom_transactions_cumulative
      - name: tjmaxx_transactions_cumulative
      - name: first_republic_transactions_cumulative
      - name: capital_one_transactions_cumulative
